### ISSUE TITLE
Revisiohistorian siirto

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#1]
(Olisi hienoa, voi olla hyvin vaikeaa...)

**Comment by TomiToivio** [comment]
PostgreSQL-gurulle tämä voisi olla mukavaa näperreltävää talviöiden ratoksi!

**Comment by pe3** [comment]
Onko tietokantaan siis kerätty "committeja". Antaisitko esimerkin miltä ne näyttävät?

**Comment by pe3** [comment]
Tarkennan vielä: Saisinko jonnekin esimerkin miltä revision historian data näyttää? Onko siis kyse SQL-datasta? Jos niin miltä yksi jonkin käyttäjän tekemä päivitys näyttää SQL-komentona ja minkä näköisiä tauluja se muokkaa?

**Comment by TomiToivio** [comment]
Siellä on sellainen tuhottoman pitkä table, jossa on käyttäjän, luvun, revisioinfon ja kirjan tunnariin liitettyjä revisioita. 

Sourcefabricin mielestä revisiohistoriaa ei voi siirtää: http://forum.sourcefabric.org/discussion/comment/27889#Comment_27889

"You are correct, there is no way to import revision history into another Booktype instance at the moment. The only way how this would be possible is to make up new format where we would export all needed information (user info, book info, chapter info, revision info) for another instance. On the other instance we would import correct user information (create new user if needed), create book, import correct revision info and etc.

There was a plan to do this. It would be used also as a good backup solution for users because they would also get entire book revision if they want."

**Comment by TomiToivio** [comment]
Ehkäpä tämänkin voi sulkea, kun on Sourcefabricin mielestä mahdotonta.
