### ISSUE TITLE
Redis restart

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#10]
Redisin uudelleenkäynnistäminen pitäisi laittaa cron jobiksi, jos ei käynnisty automaagisesti palvelimen bootatessa. Muuten Booktype on jumissa, kunnes joku käy käynnistämässä sen. 

Mitäs muuten tapahtuu, jos palvelimelle tulee monta Redisiä käyttävää alustaa? Eri porttinumerot käyttöön? Onko nyt tulossa mitään muita Redisin käyttäjiä?

**Comment by tarmot** [comment]
Ei kai croniin, ellei redis itsekseen kaatuile ja sen takia pidä sitä potkia säännöllisesti.

Mieluummin init.d-skriptit, joilla se nostetaan bootin yhteydessä ylös.

**Comment by TomiToivio** [comment]
Tämä ei oikeastaan ole Booktype-issue vaan serverin ylläpitoa, joten pistän kiinni.
