### ISSUE TITLE
Miltä osin Booktypen voisi korvata staattisella sivugeneraattorilla?

### ISSUE THREAD

**Issue by pe3** [okffi/booktype#12]
Missä määrin kirjoittamisprosessin voisi siirtää pois tietokannasta Git:in ja Markdownin varaan? Tätä yhdistelmää näkee käytettävän yhä useammin bloggaamiseen ja kirjojen kirjoittamiseen. Voisiko jokainen kirja olla oma Git-reponsa?

[NPM:llä](https://npmjs.org/) on helppo pystyttää käyttäjän omalle koneelle (Win, Mac, Linux) palvelu, joka generoi reaaliaikaista kirjan esikatseluversiota paikalliseksi kloonatusta Git-reposta ja neuvoo repon kirja-konventioiden mukaisessa editoimisessa. Kirja-repo koostuisi kansiorakenteeksi ryhmitellyistä Markdown-tiedostoista, metadatasta, kuvista ja repo-kohtaisesta kirjaprojektin kuvaavasta json-tiedostosta - vrt. [package.json](http://package.json.nodejitsu.com/).

Edelläkuvatussa arkkitehtuurissa editointihistoriaa ei enää toteutettaisi palvelukohtaisella yksittäisratkaisulla vaan hyödynnettäisiin Git-formaattia. Git tarjoaisi monipuoliset työnkulut ja valmiin työkaluekosysteemin. Monoliittisen web-palvelu-arkkitehtuurin sijaan projektissa tuotettuja työkaluja voisi hyödyntää myös muissa Git-Markdown-projekteissa, joka lisäisi niiden kiinnostavuutta. 

Git-repo-vetoisessa mallissa FLOSS Manuals toimisi Git-repojen sosiaalisena indeksinä, [npmjs.org:n](https://npmjs.org/) tapaan.

**Comment by pe3** [comment]
Tässä esimerkki kirjan kirjoittamisesta GitHubissa git:illä ja markdown:illa: [book-of-modern-frontend-tooling](https://github.com/tooling/book-of-modern-frontend-tooling). 

Jos on asentanut itselleen git:in, node:n ja grunt:in, onnistuu kirjan html- ja pdf-generoiminen seuraavalla komentosarjalla:

```
git clone https://github.com/tooling/book-of-modern-frontend-tooling.git
cd book-of-modern-frontend-tooling
npm install
grunt
```

Kirjan sisällön suunnittelu on kännissä [GitHubin issueissa](https://github.com/tooling/book-of-modern-frontend-tooling/issues), joiden luokittelu on mukautettu projektin tarpeisiin.

Tämä kaikki onnnistuu nykyään hyvin helposti jo kaikkein yksinkertaisimmilla perusvälineillä. Mitä muuta FLOSS Manuals nykyisellään tarjoaa kirjoittajille? Toki Git on hieman vaikea ja reaaliaikainen tekstin yhteiskirjoittaminen ei GitHubissa onnistu. Olisiko esimerkiksi mahdollista kytkeä [Etherpad Lite](https://github.com/ether/etherpad-lite) GitHub-repoon? Voisiko näiden tarpeiden ratkominen kiinnostaa FLOSS Manaulsin ihmisiä?

**Comment by TomiToivio** [comment]
FLOSS Manuals on käyttänyt PHP-alustaa staattisten oppaiden julkaisemiseen, mutta siihen ei enää kannata käyttää aikaa, koska kukaan ei tietääkseni varsinaisesti ylläpidä sitä. 

GitHub on tosiaan käytössä myös joissain kirjoitusprojekteissa. Se kuitenkin rajaisi osallistujat hyvin teknisiin ihmisiin? Käsittääkseni monien mielestä myös Wikimedian markup on liian hankala opeteltavaksi?

Booktype käyttää nykyisellään TinyMCE-editoria, eli teknisesti se olisi yhtä vaikea kuin WordPress. Koska TinyMCE on taiton kannalta rajoittunut editori tulee Booktype 2.0 käyttämään Aloha-editoria. Kokeilin tuota 2.0-versiota mutta en vielä osaa kommentoida Aloha-editoria sen tarkemmin.

Etherpad on hankala siinä mielessä, että se ei taida mahdollistaa juuri minkäänlaista taittoa? Eli sitä voi kyllä käyttää tekstien luonnosteluun ja ideointiin, mutta ei taida riittää lopullisen ulkoasun laatimiseen?

Sen sijaan on kyllä mielenkiintoinen idea, että kirjat olisivat Git-repositorioita ja niitä vedettäisiin vaikka automaattisesti palvelimelle. Palvelimelle voisi asentaa jonkun HTML-editorin, jolla voi editoida kirjoja vaikka ei osaisi käyttää esimerkiksi GitHubia. 

Luultavasti kirjojen pitäisi silloin olla HTML-tiedostoja, jotta niitä voisi editoida mahdollisimman monella erilaisella editorilla? 

Tämän lisäksi tulisi sellainen pieni ongelma, että jonkun pitäisi jatkuvasti käydä siivoamassa käsin mergejä.

**Comment by TomiToivio** [comment]
Itse asiassa fi.flossmanuals.net pushasi oppaiden HTML-versiot automaattisesti GitHub-repoon, mutta se oli tarkoitettu vain varmuuskopiointimenetelmäksi.

Teknisesti ottaen olisi kuitenkin ollut mahdollista käydä editoimassa oppaita GitHubissa ja vetää muutokset takaisin serverille.

**Comment by pe3** [comment]
Etherpadiin löytyy [Markdown-plugari](http://mclear.co.uk/2013/04/11/markdown-editing-and-export-in-etherpad/), jota en ole kokeillut ja muutenkin se oli vaan heitto.

Nopeesti kokeillen en heti keksinyt mihin taittotarpeisiin Markdown ei riittäisi. [Handbrake-oppaasta](http://books.okf.fi/handbrake/peruskaytto/):

---

# Peruskäyttö

Kun käynnistät **Handbraken**, sinun pitäisi nähdä alla oleva ikkuna. 

![handbrake_installed_windows](http://books.okf.fi/handbrake/peruskaytto/static/Handbrake-handbrake_installed_windows-fi.jpg)

Nyt selostan Handbraken peruskäytön, eli Handbraken käytön muuntamaan DVD-tiedostoja internetissä jaettaviksi **mp4**-tiedostoiksi. **

Ensin sinun tulisi laittaa DVD-levy tietokoneesi DVD-soittimeen. </span> 

Sen jälkeen sinun pitäisi napsauttaa Browse-nappia, joka on Source-kohdan (lähde) vieressä ohjelman ikkunassa.

![handbrake_basic_window_1.5](http://books.okf.fi/handbrake/peruskaytto/static/Handbrake-handbrake_basic_window_1-5-fi.jpg)

Tämän napin napsauttamisen jälkeen alla olevan ikkunan tulisi avautua.

![handbrake_basicl_windows](http://books.okf.fi/handbrake/peruskaytto/static/Handbrake-handbrake_basicl_windows-fi.jpg)

Vieritä alas löytääksesi DVD:n tällä listalla ja napsauta sen vieressä olevaa plus-merkkiä: 

![handbrake_basic_windows2](http://books.okf.fi/handbrake/peruskaytto/static/Handbrake-handbrake_basic_windows2-fi.jpg)

Näet nyt tiedostot DVD-levyn sisällä. Tämä ei välttämättä näytä kovinkaan ymmärrettävältä, jos et ole koskaan avannut DVD-levyä tällä tavalla. Meidän ei tarvitse tietää paljonkaan DVD-levyn rakenteesta käyttäessämme Handbrakea. Tässä vaiheessa täytyy vain tietää, että VIDEO_TS -hakemisto sisältää tiedot videotiedostoista. Valitse siis vain VIDEO_TS -hakemisto (älä kaksoisnapsauta, pelkästään korosta tämä hakemisto) ja napsauta OK. Seuraava ikkuna ilmestyy näkyviin:

![handbrake_basic_windows3](http://books.okf.fi/handbrake/peruskaytto/static/Handbrake-handbrake_basic_windows3-fi.jpg)

Edellinen ikkuna on esillä jonkin aikaa, kun Handbrake analysoi DVD-levyn rakennetta.

Voit nähdä lähdeikkunan alla alueen, jossa lukee "Title:" (Otsikko) ja "Chapters:" (Luvut). Voit jättää tämän alueen koskemattomaksi. Tämä enkoodaa kaiken DVD-levyllä olevan informaation. 

## Otsikkojen ja kappaleiden valinta

Voit valita ainoastaan yhden "otsikon" (yleensä kokonainen elokuva DVD-levyllä) tai valita "lukuja" (yleensä elokuvan osa, joka on tehty DVD-levyllä navigointi helpommaksi).

**Tässä tapauksessa voit valita otsikoita (**Titles**) ja kappaleita (**Chapters**) Handbraken oletusikkunan lähde-osassa (Source).**

![handbrake_basic_chapters1](http://books.okf.fi/handbrake/peruskaytto/static/Handbrake-handbrake_basic_chapters1-fi.jpg)

Voit nähdä eri otsikoiden (filmien) pituudet, jotta voit päättää, minkä niistä valitset.

## Ulostulotiedoston ja formaatin valinta

Ensin meidän täytyy asettaa ulostulohakemisto tiedostolle, jonka luomme. Napsauta "Browse"-nappia (selaa) ikkunan kohde-osassa (Destination):

![handbrake_basic_windows4_1](http://books.okf.fi/handbrake/peruskaytto/static/Handbrake-handbrake_basic_windows4_1-fi.jpg)

Nyt näemme tiedostoselaimen.

![handbrake_basic_windows5](http://books.okf.fi/handbrake/peruskaytto/static/Handbrake-handbrake_basic_windows5-fi.jpg)

Valitse tietokoneeltasi hakemisto, johon mp4-tiedosto luodaan ja tallennetaan. Anna tiedostonimi "File Name" -laatikkoon (tiedostonimi) ja jätä oletusarvoksi mp4 laatikkoon "Save as Type" (tallenna muodossa). Voit muuttaa tämän toiseen tiedostomuotoon jos tahdot, mutta tässä perusjohdannossa Handbrakeen jätämme sen muotoon mp4.

Tämän jälkeen voit aloittaa prosessin enkoodaamalla DVD:n mp4-tiedostoon napsauttamalla isoa "Start"-nappia ruudun vasemmassa yläosassa, kuten alla näytetään.

![handbrake_basic_windows6](http://books.okf.fi/handbrake/peruskaytto/static/Handbrake-handbrake_basic_windows6-fi.jpg)

Kun enkoodausprosessi alkaa, näet mustan ikkunan, jossa näkyy prosessin eteneminen ja kuinka kauan se vielä kestää.

![handbrake_basic_windows7](http://books.okf.fi/handbrake/peruskaytto/static/Handbrake-handbrake_basic_windows7-fi.jpg)

Jos et ole nähnyt tällaista ikkunaa, se tunnetaan DOS-ikkunana tai komentorivinä.

Kun prosessi on valmis, sinun tulisi käyttää VLC-soittimen kaltaista ohjelmaa testataksesi tiedostoa, jonka olet luonut. Tahdot ehkä ladata sen nettiin videonjakosivustolle, kuten **Archive.org** tai **Blip.tv**.

**Comment by pe3** [comment]
@TomiToivio Mä tallentaisin kirjat Markdownina (ja sen sisäänhän voi tarvittaessa kirjoittaa HTML:ääkin). Nimenomaan sen ympärille on rakentumassa erittäin aktiivinen ekosysteemi. Tsekkaa mm [78 Tools for Writing and Previewing Markdown](http://mashable.com/2013/06/24/markdown-tools/). Esimerkiksi Dropboxin avulla kirjaprojektit olis mahdollista tuoda helppokäyttöisesti erilaisten natiivieditorien ulottuville.

**Comment by TomiToivio** [comment]
Tuota Git-ideaa olisi mielenkiintoista kokeilla pidemmällä tähtäimellä. Tässä vaiheessa pelkkä Booktypekin tuntuu ylimitoitetulta resursseihin nähden. ;) 

Veikkaan, että isoin ongelma Gitin käytössä olisi pitää merget kasassa. Eli joku joutuisi jatkuvasti siistimään niitä käsin. Pelkästään tämä tekisi operaatiosta työlään, minkä lisäksi tulisi erilaisten editoriviritelmien säätäminen.

**Comment by pe3** [comment]
@TomiToivio onko kirjaprojekteilla yhtä tai useampaa vetäjä-henkilöä, jotka voivat katsoa kontribuutioiden perään? githubin pull-request:han on tehokas väline tähän. kiinnostaisko sua tulla [22.2. open data brunssille](http://pad.okfn.org/p/odd2014_helsinki) funtsaamaan jatkoja. itseäni kiinnostaa mm. suomenkielisen github-kirjoittajille [oppimateriaalin koostaminen](http://pad.okfn.org/p/intro-to-git-and-hub).

**Comment by TomiToivio** [comment]
Kas, missasin tuon idean. Ei se mitään, koska olin silloin muutenkin flunssassa.

**Comment by TomiToivio** [comment]
Eikös näitä voida pohtia osana Open Education-ryhmän booksprint-projektia? 

Luonnollisesti tuotettavalle materiaalille pitää olla editointi- ja julkaisualusta, mutta mielestäni tekninen alusta on kumminkin toissijainen kysymys kollaboratiivisen kirjoittamisen menetelmiin verrattuna. Kun niitä kirjoja ei kuitenkaan saa kirjoitettua ihan Wikipedia-tyyppisen satunnaisen osallistumisen pohjalta. Muutenhan Wikibooks olisi tuottanut jo tuhansia valmiita kirjoja.

Eli tästä muokkaamaan Suomeen sopivaa menetelmää: http://books.okf.fi/booksprint/johdanto/

**Comment by TomiToivio** [comment]
Täällä on kilpaileva alusta jota voisi testata: https://github.com/TomiToivio/PubSweet

(Veikkaan että on järkevintä pysyä Booktypessä toistaiseksi.)

**Comment by TomiToivio** [comment]
Toinenkin kilpailija, jonka WordPress-pohjaisuus olisi kyllä valtava etu: https://github.com/TomiToivio/pressbooks

Paras varmaankin pysyä Booktypessä, mutta ajattelin testailla noita huvin vuoksi.

**Comment by TomiToivio** [comment]
Pikainen evaluaatio Pressbooksista verrattuna Booktypeen:
- Pressbooks vaatii tuhottomaan kalliin lisenssin suljetun komponentin PDF-vientiin, mikä oikeastaan pilaa kaiken.
- Editori ei näytä olevan tarpeeksi kehittynyt (jotain pieniä lisäyksiä WordPressin peruseditoriin).
- Kollaboratiiviseen kirjoittamiseen ei ole mitään viestintäkanavia.  
- tavallisia WordPress-lisäosia ja teemoja ei saa käyttöön, joten kustomointi ei ole sen helpompaa.

**Comment by TomiToivio** [comment]
Oikeastaan tämä oli sittenkin hyvä idea. Mikäs olisi hyvä tapa säilyttää kirjojen tiedostoja? Siis yksinkertaisin kuviteltavissa oleva formaatti, jota voi editoida mahdollisimman monella erilaisella editorilla. Onko Markdown paras? Eikös HTML olisi yleismaailmallisin?

Ja miten kirjat saisi jaettua esimerkiksi Gitin kautta ilman että joku joutuisi käyttämään koko elämänsä mergejen tekemiseen?

**Comment by apoikola** [comment]
Markdownina on nyt julkaistu ainakin My Data -selvitys https://github.com/okffi/mydata

**Comment by TomiToivio** [comment]
Heitin ton Datademo-ehdotukseksi, mutta olin niin innoissani etten muistanut selittää miten se liittyy demokratiaan. :)

**Comment by TomiToivio** [comment]
Tosin materiaali pitäisi populismin takia saada jaettua Gitin lisäksi jonkun Dropboxin kautta, että muutkin kuin open source -nörtit voi osallistua.

**Comment by TomiToivio** [comment]
Tämä ei oikein innostanut ihmisiä Datademossa, joten mietitään sitä sitten taas joskus: https://trello.com/c/NeYOfbni/4-hajautettu-yhteisokirjoittaminen
