### ISSUE TITLE
Repon nimi?

### ISSUE THREAD

**Issue by pe3** [okffi/booktype#13]
Miksi muuten tämän repon nimi on "booktype"?

**Comment by TomiToivio** [comment]
Oikeastaan tämän pitäisi olla forkattu suoraan Booktypestä.

Tämähän on repo vain books.okf.fi Booktypelle. Jos sinne asentelee muita kustomoitavia ohjelmia, pitää niille tehdä omat reponsa. 

Tämän vuoksi muuten pidän esimerkiksi WordPressistä. Jos olisi WordPress-pohjainen saitti, olisi erilliset repot kustomoidulle teemalle ja mahdollisille omille lisäosille, mutta WordPress itsessään ei edes tarvitsisi repoa, koska sitä ei tarvitse muutella. Booktypessä vastaava kustomointi on Booktype-repossa. Mielestäni se on ihan väärin.
