### ISSUE TITLE
Sähköposti

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#14]
Booktypen pitäisi voida lähettää sähköpostia salasanan nollaamista ja notifikaatioita varten. 

Mitäs tämän suhteen tehtäisiin? Oikeastaan tämä on serverikysymys eikä liity Booktypeen.

**Comment by jaakkokorhonen** [comment]
Lähtevän postin palvelin on smtp.saimanet.net.

**Comment by apoikola** [comment]
Froidessa (tietopyyntösofta) on https://postmarkapp.com/ käytössä... 10 000 meiliä lähtee ilmaiseksi.  

https://froide.readthedocs.org/en/latest/herokudeployment/

**Comment by TomiToivio** [comment]
smtp.saimane.net näyttäisi toimivan.
