### ISSUE TITLE
Oauth ja error.log

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#17]
Djangon OAuth heittää jatkuvasti (turhia) virheilmoituksia Apachen error.logiin.

Näyttääpi sille, että Djangon Oauthia on tämän projektin resursseilla ihan turhaa ryhtyä korjaamaan. 

Ignoroidaanko error.log vai otetaanko Oauth pois?

**Comment by apoikola** [comment]
tietämättä, millaisia ja miten vaarallisia erroreita, niin ehkä se Oauthin poistaminen voi olla ihan ok. Kannattaa dokumentoida kuitenkin, että mitä kävi.

**Comment by jaakkokorhonen** [comment]
Niin ei siinä kai mitään vaaraa ole kun tiedetään mitä ilmoitukset on.

**Comment by TomiToivio** [comment]
Itse asiassa OAuth on vähän kyseenalainen Booktypessä, koska se johtaa nopeasti siihen että ihmisillä on useampi user account, ja kun revisiohistoria on sidottu user accountteihin tulee ylläpidon kannalta erittäin epämiellyttävä tilanne, jos joku pyytää vaikka yhdistämään käyttäjätilinsä.
