### ISSUE TITLE
Sivusto kiinni resurssipulan vuoksi

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#18]
Laitan sivuston toistaiseksi kiinni, koska minulla ei ole resursseja tähän.

Jos joku tuntee olevansa hyvin varakas voi ilmoittautua vapaaehtoiseksi jatkamaan toimintaa.

**Comment by apoikola** [comment]
Minkälaisia resursseja olisi tarpeen? Osaamista / aikaa / rahaa / henkistä tukea?
