### ISSUE TITLE
Math markup, Aloha ja Booktype 2.0

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#19]
Käsittääkseni tärkein toive oli saada Booktypen editori ymmärtämään matematiikkakaavioita. 

Ne ovat tulossa Booktypen versioon 2.0., jossa siirrytään juuri näiden vuoksi käyttämään Aloha-editoria: http://forum.sourcefabric.org/discussion/16062/mathml-support-and-few-other-questions

Pitäisikö siis hypätä versioon 2.0? 

Liian flunssa tehdä mitään, kunhan ihmettelen...

**Comment by apoikola** [comment]
+1 versiolle 2.0. Aikanaan avoimet oppikirjat ry. evaluoi Booktypen ja silloin matikkaeditorin puute kallisti viisarin LaTexin puolelle, jossa toki on huomattavasti suurempi oppimiskynnys ei-teknisille.

Vähän off-topic: Keskiviikkona oli puhetta, että koitetaan saada puhallettua asiaan henkeä niin, että Booktype -tekemiselle saadaan myös rahoitusta, ettei mene flunssaisesta selkänahasta. Yksi rahoituskuvio olisi juurikin viedä homma osaksi Avoimet oppikirjat -kehitystä ja jotain suurempaa hanketta.

Ensihätään ennen hankekuvioita @tarmot on sinuun yhteydessä sen puolesta, että voitaisiinko OKFFI:n vähäisillä, mutta ei kuitenkaan täysin olemattomilla resursseilla jotenkin tukea tekemistä.

**Comment by TomiToivio** [comment]
Versio 2.0 on kuitenkin vielä keskeneräinen. 

Eli vaihtoehdot ovat: 
- Ei tehdä mitään ennen kuin 2.0 julkaistaan virallisesti 
- Pompataan suoraan versioon 2.0 ja ihmetellään mitä siitä puuttuu

Ei jaksa keskittyä noihin flunssassa, en ole sen tarkemmin jaksanut katsoa mitä versiossa 2.0 on tällä hetkellä valmiina ja mitä puuttuu.

**Comment by TomiToivio** [comment]
Ilmeisesti Sourcefabricissa ideana olisi integroida tämä jossain vaiheessa virallisesti Booktypeen: http://editor.oerpub.org/ 

Mutta joku versio olisi ollut jo käytössä.

Ei näistä oikein saa selvää, flunssa jatkuu.

**Comment by TomiToivio** [comment]
Testasin Booktype 2.0 ja se on niin vaiheessa, ettei kannata vaivautua vielä päivittelemään. 

Toisaalta tätä vanhaa versiota ei myöskään kannata kustomoida, koska Booktype 2.0 on ihan erilainen. Menee kustomointi hukkaan.

**Comment by TomiToivio** [comment]
Pitäisi kaivaa noita TinyMCE-muotoilukokeiluja ja muita ylimääräisiä testailuja pois sieltä, ei niitä jaksa viimeistellä kun kaikki menee uusiksi versiossa 2.0.
