### ISSUE TITLE
Projekti kiinni?

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#21]
Projekti ei saanut rahoitusta, joten näillä näkymin mitään aktiviteettia ei ole odotettavissa.

**Comment by apoikola** [comment]
ei ehkä ihan näin nopeasti kannata laittaa lappua luukulle. Rahoitusta voidaan hakea ja jos päädytäänkin sulkemaan, niin olisi varmaan hyvä julkaista ainakin olemassaolevat kirjat staattisina versioina.

**Comment by TomiToivio** [comment]
Ainakin se on taas jumissa puoli vuotta jos mietitään uutta rahoitusmahdollisuutta.

**Comment by TomiToivio** [comment]
Onkos mitään ideaa tämän jatkamiseen? :)

**Comment by apoikola** [comment]
Ei nyt juuri ja heti, mutta tämän voisi ottaa vaikka OKFFI:n hallituksessa puheeksi.
