### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#22]
Innostuin hieman testailemaan ja nyt Booktypessä on esimerkiksi API: http://fi.flossmanuals.net/api/book/?format=json

Mitä tällä voisi tehdä? 

Djangoa voi tosiaan laajentaa aika helposti.

**Comment by apoikola** [comment]
Voisiko tolla tehdä esim. rinnakkais html-julkaisun booktype-kirjoista johonkin toiselle palvelimelle, jolloin ne olisivat saatavilla backuppina myös, jos Booktype on joskus poissa pelistä?

**Comment by TomiToivio** [comment]
Booktype 2.0 on niin pahasti kesken että asensin 1.6 uudelleen.

**Comment by TomiToivio** [comment]
Pitäisi tehdä kustomoinnit erilliseen applikaatioon, ettei tästä tule liian monimutkaista.

**Comment by TomiToivio** [comment]
Ollaan pohdittu ranskalaisten ja englanninkielisten kanssa miten alusta kustomoidaan, mutta kun sitä on liian aikaista tehdä ennen kuin Booktype 2.0 tulee virallisesti valmiiksi, niin asia ei oikein ole edennyt. Ilmeisesti tahtovat kumminkin tehdä erillisen frontendin Booktypen eteen.
