### ISSUE TITLE
Serverin siirto?

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#23]
Ajattelin että Booktypen voisi siirtää tietopyynto.okf.fi-serverille, koska 2.0 käyttää Celeryä ja muita samoja systeemejä kuin Froide. 

Näiden Django-alustojen vuoksi joutuu sudottamaan niin paljon, että epäilen sen ennemmin tai myöhemmin sotkevan väkisinkin jonkun muun projektin viritelmät.

**Comment by apoikola** [comment]
Lyhyellä tähtäimellä: @jaakkokorhonen kommentoinee, miten sopii tietopyynto.fi kuvioihin... minuun puolestani kaikki synergiat ovat aina hyviä.

Pitkällä tähtäimellä: olisiko se "dokkerointi" mahdollinen tapa hallita samoilla servereillä useampia sovelluksia helposti?

**Comment by TomiToivio** [comment]
Noista olisi luultavasti hyötyä jos samanlaisia sivuja olisi kymmeniä, mutta tässä vaiheessa olisi vain ylimääräistä vaivaa.

**Comment by jaakkokorhonen** [comment]
Nii mitäs jos dokkerisois booktypen kun se on kuitenkin meidän tuotantosofta? Ainakin vois pyytää asiaa booktypen main branchin ylläpitäjiltä.
