### ISSUE TITLE
Booktype 2.0

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#24]
Päivittelin Booktypen versioon 2.0, koska sivuja on pakko kustomoida ja vanhaan versioon 1.6. ei kannata enää koskea. 

Se eroaa vanhasta valtavasti ja esimerkiksi lokalisaation saa tehdä melkein kokonaan uusiksi.

**Comment by apoikola** [comment]
onkos käännökset käännettävissä jossain esim. Transifex?

**Comment by TomiToivio** [comment]
Tuolla: https://www.transifex.com/organization/sourcefabric/dashboard/booktype

**Comment by apoikola** [comment]
Liityin nyt tiimiin, en suoraan lupaa kaikkia lokalisaatioita hakata sisään, mutta käännöstyö on kuitenkin ihan tehtävissä ja siihen saa varmaan mukaan muutaman muunkin vapaaehtoisen.

**Comment by TomiToivio** [comment]
Joo, en tiedä onko sillä hirveä kiire, koska ainakin viimeksi kokeillessani 2.0 oli vielä pahasti kesken...
