### ISSUE TITLE
Nginx sotkee?

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#25]
Joku käy aina laittamassa serverillä päälle Nginx-palvelimen, niin että Apache ei pääse käynnistymään ja Booktypen sijasta tulee Nginx bad gateway. Saisko ton asetukset niin ettei se sotke Apachea? Mikä sitä yleensä käyttää?

**Comment by tarmot** [comment]
Se on se CKAN, jota äijät asentelee sen oletusasennusskriptillä, joka rikkoo kaiken tieltään. Jaakko, kuka on vastuussa siitä ckanista?

**Comment by jaakkokorhonen** [comment]
Joo pitää ottaa se pois.

**Comment by TomiToivio** [comment]
Menikö se jo? Laitan kiinni.
