### ISSUE TITLE
Varmuuskopiointi

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#6]
Tietokannan ja muun sisällön automaattinen varmuuskopiointi.

**Comment by pe3** [comment]
Onko ajatuksia miten tämä kannattais organisoida? Minne kopioidaan ja millä välineellä?

**Comment by apoikola** [comment]
@jaakkokorhonen @tarmot mikäs olikaan lopputulema varmuuskopiointiasioiden suhteen? Tämä on varmasti yleisemmän tason ratkaistava juttu, eikä pelkästään Booktypen kohdalla.

**Comment by tarmot** [comment]
Kaikki levytila varmuuskopioituu automaattisesti. Laitevian takia ei tarvitse siis erillistoimenpiteitä. Mutta toki jos halutaan datan korruptoitumiselta varautua ja pitää vanhoja backuppeja, pitää ne jotenkin järjestää.

@jaakkokorhonen, Saimaltahan piti saada myös varmuuskopioimatonta scratch-tilaa halvemmalla? Sitä voisi ottaa käyttöön, niin siinä olisi hyvä paikka tehdä säännöllisiä inkrementaalisia backup-dumppeja. Jotta sitten on jotain historiallista dataa jos havaitaan jonkin menneen solmuun.

**Comment by jaakkokorhonen** [comment]
Meillä on nyt levytilabudjetti sadalle gigalle 9€ per kk. Ehdotan että
kerätään 3-500 gigaa avointa dataa (2017 mennessä) ja aletaan vasta sitten
murehtimaan kustannuksista :)

2013/12/19 Tarmo Toikkanen notifications@github.com

> Kaikki levytila varmuuskopioituu automaattisesti. Laitevian takia ei
> tarvitse siis erillistoimenpiteitä. Mutta toki jos halutaan datan
> korruptoitumiselta varautua ja pitää vanhoja backuppeja, pitää ne jotenkin
> järjestää.
> 
> @jaakkokorhonen https://github.com/jaakkokorhonen, Saimaltahan piti
> saada myös varmuuskopioimatonta scratch-tilaa halvemmalla? Sitä voisi ottaa
> käyttöön, niin siinä olisi hyvä paikka tehdä säännöllisiä inkrementaalisia
> backup-dumppeja. Jotta sitten on jotain historiallista dataa jos havaitaan
> jonkin menneen solmuun.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/okffi/booktype/issues/6#issuecomment-30913605
> .

## 

tjaakko

**Comment by jaakkokorhonen** [comment]
Palveluun kuuluu viikottainen full backup ja päivittäinen snapshot eli muuttuneiden päivitys. Hyvä idea varmaan testata asiaa jossain vaiheessa käytännössä, esim pyytämällä tyyliin viime viikon tiistain tilanne johonkin tiettyyn hakemistoon. Tämähän oli speksattu jo kilpailutusvaiheessa ja ihan vakio toiminto tämmösissä tuotantotason palveluissa. Ei todellakaan jotain jota aletaan itse itsellemme näpertelemään lol.

**Comment by TomiToivio** [comment]
Yksi hauska tapa varmuuskopioida oli Bookipublisherin arkiston pushaaminen automaattisesti tänne: https://github.com/TomiToivio/fifm-archive

Bookipublisher kuitenkin poistuu käytöstä ja tuossa on vain oppaiden julkaistut versiot, eli se ei oikein toimi jatkossa.

**Comment by TomiToivio** [comment]
Mutta varmaankin voidaan sanoa, ettei tästä kannata stressata sen enempää ja sulkea issue...
