### ISSUE TITLE
Django Oauthin asentaminen?

### ISSUE THREAD

**Issue by TomiToivio** [okffi/booktype#7]

**Comment by apoikola** [comment]
Tästä oli puhetta myös Froide -projektin suhteen, kannattaa varmaankin tsekata samalla molempiin https://github.com/okffi/tietopyynto/issues/9

**Comment by TomiToivio** [comment]
Käyttäjätunnuksiin, kirjoihin ja ryhmiin olisi myös hyvä lisätä kenttiä. Esimerkiksi Google Author-markuppia varten tarvitsisi kentän, johon käyttäjä voi laittaa Google Plus-tunnuksensa.

Toisaalta voisi olla hyvä välttää sellaisia muutoksia, jotka forkkaavat liikaa Booktypen virallisesta versiosta, eli rajoittua templaattien muutoksiin?

Booktype-kirjojen julkaisemiseen käytetään Objavia, siihen voi käyttää Sourcefabricin tai FLOSS Manualsin yhteistä Objavia (tällä hetkellä käytössä on Sourcefabricin Objavi), mutta jos julkaisuja tahtoo muokata vielä enemmän kuin nyt on mahdollista, voi olla tarpeen asentaa erillinen Objavi.

Lisäksi Booktype pystyi aikaisemmin julkaisemaan suoraan Lulu.comiin, mutta Lulu.comin API siirtyi eläkkeelle, joten ei ole enää mahdollista.

**Comment by TomiToivio** [comment]
Omasta mielestäni isoimpien ja yleisimpien OAuth-palveluntarjojajien käyttö madaltaisi radikaalisti osallistumiskynnystä, eli populismin vuoksi Facebook ja Google.

**Comment by TomiToivio** [comment]
Etherpad Liten embeddaaminen Booktypeen olisi jotenkin houkuttelevaa. Englanninkielisessä versiossa sellainen on vain lätkäisty siihen kirjan muistiinpanot -välilehteen. 

En vain tiedä onko siitä niin paljon iloa nykyisiin muistiinpanoihin verrattuna, että pelkästään sen takia kannattaisi ylläpitää Etherpadia. Jos sellainen asennetaan joka tapauksessa serverille, voisi sen laittaa Booktypeenkin.

**Comment by tarmot** [comment]
Nykyisin kai käytetään aika paljon OKFN:n tarjoamaa padia, mutta sinänsä ei ehkä ole huono asia tarjota padia suomalaisille yleisemminkin, vähän tyyliin muistio.tieke.fi...

**Comment by TomiToivio** [comment]
Sen saa tosiaan embeddattua iframena: <iframe name='embed_readwrite' src='http://whatever.org/p/{{book.url_title}}?showControls=true&showChat=true&showLineNumbers=true&useMonospaceFont=false&userName={{ request.user.username }}' width=100% height=400></iframe>

Eli ei tarvitse laittaa mitään ylimääräistä Booktypen tietokantaan.

**Comment by TomiToivio** [comment]
Katselin noita Django Oauth-juttuja, ainakaan dokumentaatio ei ollut liian selkeää. 

Kokeilen tätä: https://help.ubuntu.com/community/Etherpad-liteInstallation

Jos Etherpad on lähinnä Booktype-projektien käytössä, niin tuskin tulee hirveästi kuormitusta. Mutta jos se leviää  yleiseen käyttöön, voi varmaan tulla vähän liikaakin. Pitäisikö sitä pitää hieman jemmassa?

**Comment by TomiToivio** [comment]
Pienen testailun perusteella Djangon Oauth-paketit eivät ihan helposti toimi ja ainakin osa sotkee lisäksi Booktypen oman autentikaation. 

Testailin lähinnä tätä Oneall-pakettia, koska se toimii hyvin WordPressissä: https://www.djangopackages.com/packages/p/django-oneall/

Kun lisää settings.py-tiedostoon AUTHENTICATION_BACKENDS = ('django_oneall.auth.OneAllAuthBackend',) Booktypen oma autentikaatio ei enää toimi.

**Comment by TomiToivio** [comment]
Tämän saa kyllä toimimaan: http://django-social-auth.readthedocs.org/en/latest/
